---
- name: Import optional extra_args file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  failed_when: false
  tags: vars

- name: Create a few directories which kdevops uses for sysbench if they do not exist
  tags: ["mkfs"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kdevops_data }}"
    - "{{ sysbench_mnt }}"

# Distro specific
- name: Install dependencies
  include_tasks: install-deps/main.yml

- include_role:
    name: create_data_partition
  tags: ["mkfs"]

- name: MySQL Docker
  ansible.builtin.import_tasks: mysql-docker/main.yaml
  when: sysbench_type_mysql_docker | bool

- name: PostgreSQL Native
  ansible.builtin.import_tasks: postgresql-native/main.yaml
  when: sysbench_type_postgresql_native | bool
