---
- name: Enable installation of packages from EPEL
  ansible.builtin.include_role:
    name: epel-release
  when:
    - ansible_distribution != "Fedora"

- name: Install ktls dependencies
  become: true
  become_method: sudo
  dnf:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - python3-cryptography
      - ktls-utils
