---
- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: ["btrfs-progs", "update-cache"]

- name: Install btrfs-progs build dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - libext2fs-dev
      - pkg-config
      - libblkid-dev
      - libzstd-dev
      - libudev-dev
      - liblzo2-dev
    state: present
  tags: ["btrfs-progs", "build-deps"]
