---
- name: Install kexec-tools and dependencies for reboot-limit on SUSE
  become: true
  become_method: sudo
  community.general.zypper:
    name:
      - kexec-tools
    state: present
    update_cache: true
  tags: ["install", "kexec"]
