---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Stop and remove MinIO container
  community.docker.docker_container:
    name: "{{ minio_container_name }}"
    state: absent
  ignore_errors: true

- name: Remove Docker network
  community.docker.docker_network:
    name: "{{ minio_docker_network_name }}"
    state: absent
  ignore_errors: true

- name: Clean up MinIO data directory
  ansible.builtin.file:
    path: "{{ minio_data_path }}"
    state: absent
  when: minio_warp_enable_cleanup | default(true) | bool

- name: Clean up temporary Warp results
  ansible.builtin.file:
    path: "/tmp/warp-results"
    state: absent

- name: Display MinIO destroy complete
  ansible.builtin.debug:
    msg: "MinIO containers and data have been cleaned up"
