---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

# Distro agnostic stuff goes below

- name: git reset kdevops
  environment:
    GIT_SSL_NO_VERIFY: true
  git:
    repo: "{{ kdevops_git }}"
    dest: "{{ kdevops_data }}"
  retries: 3
  delay: 5
  register: result
  until: not result.failed
  tags: ["kdevops_reset"]
  when:
    - kdevops_git_reset|bool

- name: Get username we are using
  command:
    cmd: whoami
  register: username_on_target
  when:
    - infer_uid_and_group|bool

- name: Set target user as a fact
  set_fact:
    target_user: "{{ username_on_target.stdout }}"
  when:
    - infer_uid_and_group|bool

- name: Run getent against the inferred target user
  getent:
    database: passwd
    key: "{{ target_user }}"
  register: getent_running_user
  when:
    - infer_uid_and_group|bool

- name: Run getent against the inferred target group
  getent:
    database: group
    key: "{{ target_user }}"
  register: getent_on_group
  when:
    - infer_uid_and_group|bool

- name: Override user and group with inferred settings if feature is enabled
  set_fact:
    data_user: "{{ target_user }}"
    data_group: "{{ ((getent_on_group.values() | first).values() | first).keys() | first }}"
  when:
    - infer_uid_and_group|bool
