---
- name: Install Fedora-specific dependencies
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - git-daemon
    state: present
  when:
    - install_linux_mirror|bool
  tags: ["mirror"]

- name: Gather service facts
  ansible.builtin.service_facts:
  tags: ["mirror"]

- name: Open the firewall on control node for git traffic
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  ansible.posix.firewalld:
    zone: libvirt
    port: 9418/tcp
    permanent: true
    immediate: true
    state: enabled
  when:
    - install_linux_mirror|bool
    - '"firewalld.service" in ansible_facts.services'
    - ansible_facts.services['firewalld.service'].status == "enabled"
  tags: ["mirror"]
