---
- name: Install libguestfs
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    update_cache: true
    name:
      - libguestfs-tools
      - isc-dhcp-client
    state: present
  tags: ['install-deps']
