# SPDX-License-Identifier: copyleft-next-0.3.1

QEMU_BUILD_SETUP_ARGS :=
QEMU_BUILD_SETUP_ARGS += qemu_build=True

# CONFIG_QEMU_BUILD_TREE_PATH, _BUILDDIR, _DESTDIR, and _BIN_PATH
# already use Kconfig "output yaml" so they land in extra_vars
# directly as qemu_build_tree_path, qemu_build_builddir,
# qemu_build_destdir, qemu_build_bin_path. The role consumes
# those names. Adding them here as well would break Make's
# foreach iteration over ANSIBLE_EXTRA_ARGS, because the values
# are Jinja templates that contain whitespace
# ({{ kdevops_controller_data_path }}/...) and foreach splits
# on whitespace.
QEMU_GIT:=$(subst ",,$(CONFIG_QEMU_BUILD_GIT))
QEMU_GIT_VERSION:=$(subst ",,$(CONFIG_QEMU_BUILD_GIT_VERSION))

QEMU_BUILD_SETUP_ARGS += qemu_git=$(QEMU_GIT)
QEMU_BUILD_SETUP_ARGS += qemu_version='$(QEMU_GIT_VERSION)'

ifeq (y,$(CONFIG_TARGET_ARCH_X86_64))
QEMU_BUILD_SETUP_ARGS += qemu_target="x86_64-softmmu"
endif

ifeq (y,$(CONFIG_TARGET_ARCH_PPC64LE))
QEMU_BUILD_SETUP_ARGS += qemu_target="ppc64-softmmu"
endif

qemu: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml
PHONY += qemu

qemu-install: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,install
PHONY += qemu-install

qemu-configure: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,configure
PHONY += qemu-configure

qemu-build: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,build
PHONY += qemu-build


qemu-help-menu:
	@echo "qemu options:"
	@echo "qemu                                 - Git clones qemu, builds and install it on localhost"
	@echo "qemu-configure                       - Configure qemu build"
	@echo "qemu-build                           - Build qemu"
	@echo "qemu-install                         - Do the install of the qemu build on localhost"
	@echo ""

HELP_TARGETS += qemu-help-menu

ANSIBLE_EXTRA_ARGS += $(QEMU_BUILD_SETUP_ARGS)
LOCALHOST_SETUP_WORK += qemu
