# SPDX-License-Identifier: copyleft-next-0.3.1
#
# QEMU build targets
#
# QEMU configuration is managed through kconfig with 'output yaml' directive.
# All QEMU variables (qemu_build, qemu_build_git, qemu_build_git_data_path,
# qemu_build_git_version, qemu_target) are automatically exported from kconfig
# to .extra_vars_auto.yaml and do not need Makefile variable extraction.
#
# See kconfigs/Kconfig.libvirt for QEMU configuration options.

qemu: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook $(ANSIBLE_VERBOSE) \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml
PHONY += qemu

qemu-install: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook $(ANSIBLE_VERBOSE) \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,install
PHONY += qemu-install

qemu-configure: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook $(ANSIBLE_VERBOSE) \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,configure
PHONY += qemu-configure

qemu-build: $(KDEVOPS_EXTRA_VARS)
	$(Q)ansible-playbook $(ANSIBLE_VERBOSE) \
		$(KDEVOPS_PLAYBOOKS_DIR)/build_qemu.yml \
		--extra-vars=@./extra_vars.yaml --tags vars,build
PHONY += qemu-build


qemu-help-menu:
	@echo "qemu options:"
	@echo "qemu                                 - Git clones qemu, builds and install it on localhost"
	@echo "qemu-configure                       - Configure qemu build"
	@echo "qemu-build                           - Build qemu"
	@echo "qemu-install                         - Do the install of the qemu build on localhost"
	@echo ""

HELP_TARGETS += qemu-help-menu

LOCALHOST_SETUP_WORK += qemu
