---
- name: Install pynfs build dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - gcc
      - git-core
      - make
      - libkrb5-dev
      - python3-dev
      - python3-setuptools
      - swig
      - python3-gssapi
      - python3-ply
      - python3-standard-xdrlib
    state: present
    update_cache: true
  tags: ["pynfs", "deps"]
