# SPDX-License-Identifier GPL-2.0+
---
# Our sensible defaults for the pynfs role.
#
# We default to not run tests.
kdevops_run_pynfs: false
pynfs_pnfs_block: false

pynfs_data: "{{ data_path }}/pynfs"
