---
- name: Install kdc dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - krb5-admin-server
      - krb5-kdc
      - krb5-user
    state: present
    update_cache: true
