---
- name: Install kdevops generic dependencies
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - bison
      - flex
      - m4
      - bc
      - sed
      - ncurses-devel
    state: present
