---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install systemd-journal-remote
  ansible.builtin.include_tasks: install-deps/main.yml
- name: Set up the server /etc/systemd/journal-remote.conf
  tags: ["journal"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.template:
    src: "journal-remote.conf.j2"
    dest: "/etc/systemd/journal-remote.conf"
    force: true
    trim_blocks: true
    lstrip_blocks: true
  when:
    - devconfig_enable_systemd_journal_remote|bool

- name: Use custom systemd-journal-remote.service to disable SSL
  tags: ["journal"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.template:
    src: "systemd-journal-remote.service.j2"
    dest: "/lib/systemd/system/systemd-journal-remote.service"
    force: true
    trim_blocks: true
    lstrip_blocks: true
  when:
    - devconfig_enable_systemd_journal_remote|bool
    - devconfig_systemd_journal_use_http|bool

- name: Ensure our user is part of the systemd-journal-remote group
  tags: ["journal"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: systemd-journal-remote
    append: true
  when:
    - devconfig_enable_systemd_journal_remote|bool

- name: Restart systemd-journal-remote on the server
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.systemd_service:
    name: systemd-journal-remote.service
    daemon_reload: true
    enabled: true
    state: restarted
  when:
    - devconfig_enable_systemd_journal_remote|bool

- name: Ensure systemd-journal-remote.service is running on the server
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.systemd_service:
    name: systemd-journal-remote.service
    state: started
  when:
    - devconfig_enable_systemd_journal_remote|bool

- name: Set group sticky bit for /var/log/journal/remote/
  tags: ["journal"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.file:
    path: "/var/log/journal/remote/"
    owner: systemd-journal-remote
    group: systemd-journal-remote
    mode: u=rwx,g=rwx,o=rx,g+s
    recurse: true
    state: directory
  when:
    - devconfig_enable_systemd_journal_remote|bool
