---
- name: Start the memory_fragmentation tracker
  ansible.builtin.include_tasks: run.yml
  tags: [do_run]

- name: Collect the memory_fragmentation data and render plot
  ansible.builtin.include_tasks: collect.yml
  tags: [do_collect]
