---
- name: Install krb5 dependencies
  become: true
  become_method: sudo
  community.general.zypper:
    name:
      - krb5
      - krb5-client
      - kernel-default
    state: present
    force_resolution: true

- name: Reboot system to make the new kernel and modules take effect
  become: true
  become_method: sudo
  ansible.builtin.reboot:
