---
# Common monitoring setup tasks

- name: Debug monitoring collection start
  ansible.builtin.debug:
    msg: |
      Starting monitoring collection
      monitor_developmental_stats: {{ monitor_developmental_stats | default(false) }}
      monitor_folio_migration: {{ monitor_folio_migration | default(false) }}
      enable_monitoring: {{ enable_monitoring | default(false) }}
      kdevops_run_fstests: {{ kdevops_run_fstests | default(false) }}

- name: Set monitoring results path
  ansible.builtin.set_fact:
    monitoring_results_path: "{{ monitoring_results_base_path | default(topdir_path + '/workflows/fstests/results/monitoring') }}"

- name: Create local monitoring results directory
  ansible.builtin.file:
    path: "{{ monitoring_results_path }}"
    state: directory
  delegate_to: localhost
  run_once: true