---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: deps

- name: Install mmtests build dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - build-essential
      - git
      - perl
      - cpanminus
      - libmath-gradient-perl
      - r-base
      - r-base-dev
      - libnuma-dev
      - libmath-gradient-perl
    state: present
    update_cache: true
  tags: ["deps"]

- name: Install mmtests runtime dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - numactl
      - fio
      - sysstat
      - procps
      - util-linux
      - coreutils
      - time
      - bc
      - psmisc
    state: present
    update_cache: true
  tags: ["deps"]

- name: Install mmtests monitoring dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - trace-cmd
      - perf-tools-unstable
    state: present
    update_cache: true
  tags: ["deps"]
  ignore_errors: true
