---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_items:
    - "../extra_vars.yaml"
  tags: vars

- name: Create multi-filesystem results directory
  ansible.builtin.file:
    path: "{{ ai_multifs_results_dir }}"
    state: directory
    mode: "0755"

- name: Create mount point directory
  ansible.builtin.file:
    path: "{{ ai_multifs_mount_point }}"
    state: directory
    mode: "0755"

- name: Unmount any existing filesystem on mount point
  ansible.posix.mount:
    path: "{{ ai_multifs_mount_point }}"
    state: unmounted
  ignore_errors: true

- name: Install required filesystem utilities
  ansible.builtin.package:
    name:
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
    state: present

- name: Filter enabled filesystem configurations
  ansible.builtin.set_fact:
    enabled_fs_configs: "{{ ai_multifs_configurations | selectattr('enabled', 'equalto', true) | list }}"

- name: Display enabled filesystem configurations
  ansible.builtin.debug:
    msg: "Will test {{ enabled_fs_configs | length }} filesystem configurations: {{ enabled_fs_configs | map(attribute='name') | list }}"

- name: Validate that device exists
  ansible.builtin.stat:
    path: "{{ ai_multifs_device }}"
  register: device_stat
  failed_when: not device_stat.stat.exists

- name: Display device information
  ansible.builtin.debug:
    msg: "Using device {{ ai_multifs_device }} for multi-filesystem testing"

- name: Create filesystem configuration summary
  ansible.builtin.copy:
    content: |
      # AI Multi-Filesystem Testing Configuration
      Generated: {{ ansible_date_time.iso8601 }}
      Device: {{ ai_multifs_device }}
      Mount Point: {{ ai_multifs_mount_point }}
      Results Directory: {{ ai_multifs_results_dir }}

      Enabled Filesystem Configurations:
      {% for config in enabled_fs_configs %}
      - {{ config.name }}:
          Filesystem: {{ config.filesystem }}
          mkfs command: {{ config.mkfs_cmd }}
          Mount options: {{ config.mount_opts }}
      {% endfor %}
    dest: "{{ ai_multifs_results_dir }}/test_configuration.txt"
    mode: "0644"
