---
- name: Import optional extra_args file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  failed_when: false
  tags: vars

- name: Generate kdevops ansible.cfg
  template:
    src: "ansible.cfg.j2"
    dest: "{{ topdir_path }}/ansible.cfg"
