---
- name: Ensure the controller user is in the libvirt, kvm, and libvirt-qemu groups
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - libvirt
      - kvm
      - libvirt-qemu
    append: true
  when: not (libvirt_session | default(false) | bool)
  tags: do_configure
