---
- name: Install libvirt / kvm dependencies
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - qemu-system-x86
    state: present

- name: Enable libvirtd
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    masked: false

- name: Make sure libvirtd is running
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    state: started
    name: libvirtd

- name: Enable virtnetworkd
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: virtnetworkd
    enabled: true
    masked: false

- name: Make sure virtnetworkd is running
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    state: started
    name: virtnetworkd
