---
- name: Debian/Ubuntu distribution specific setup
  ansible.builtin.import_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: SUSE distribution specific setup
  ansible.builtin.import_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'

- name: RedHat distribution specific setup
  ansible.builtin.import_tasks: redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
