---
- name: Import optional distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      skip: true
  tags: vars

- name: Debian/Ubuntu distribution specific setup
  ansible.builtin.import_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: SUSE distribution specific setup
  ansible.builtin.import_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'

- name: RedHat distribution specific setup
  ansible.builtin.import_tasks: redhat/main.yml
  when:
    - ansible_facts['os_family']|lower == 'redhat'
    - ansible_facts['distribution']|lower != "fedora"

- name: Fedora distribution specific setup
  ansible.builtin.import_tasks: fedora/main.yml
  when: ansible_facts['distribution']|lower == "fedora"
