---
- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: install

- name: Install libvirt / kvm dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-daemon-config-network
      - libvirt-clients
      - qemu-kvm
      - qemu-system-x86
      - qemu-utils
    state: present
  tags: install

- name: Enable libvirtd
  become: true
  become_method: sudo
  systemd:
    name: libvirtd
    enabled: true
    masked: false

- name: Make sure libvirtd is running
  become: true
  become_method: sudo
  systemd:
    state: started
    name: libvirtd
