---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  failed_when: false
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true

- name: Check if PCI-E sysfs driver_override files exist
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  vars:
    sysfs_override: "{{ pcie_sysfs_device_path_prefix }}/{{ item.pcie_id }}/driver_override"
  ansible.builtin.stat:
    path: "{{ sysfs_override }}"
  with_items: "{{ pcie_passthrough_devices }}"
  loop_control:
    label: "{{ item.pcie_human_name }}"
  register: libvirt_pcie_driver_override_stats
  when: pcie_passthrough_enable | bool

- name: Enable libvirt to use PCI-E sysfs driver_override files
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    group: "{{ libvirt_qemu_group }}"
    mode: "0664"
  with_items: "{{ libvirt_pcie_driver_override_stats.results }}"
  loop_control:
    label: "{{ item.stat.path }}"
  when:
    - pcie_passthrough_enable | bool
    - item.stat.exists

- name: Check if PCI-E sysfs unbind files exist
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  vars:
    sysfs_unbind: "{{ pcie_sysfs_device_path_prefix }}/{{ item.pcie_id }}/unbind"
  ansible.builtin.stat:
    path: "{{ sysfs_unbind }}"
  with_items: "{{ pcie_passthrough_devices }}"
  loop_control:
    label: "{{ item.pcie_human_name }}"
  register: libvirt_pcie_driver_unbind_stats
  when: pcie_passthrough_enable | bool

- name: Enable libvirt to use PCI-E sysfs unbind files
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    group: "{{ libvirt_qemu_group }}"
    mode: "0220"
  with_items: "{{ libvirt_pcie_driver_unbind_stats.results }}"
  loop_control:
    label: "{{ item.stat.path }}"
  when:
    - pcie_passthrough_enable | bool
    - item.stat.exists

- name: Deploy udev 10-qemu-hw-users.rules which enables libvirt to use vfio subsystem
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.template:
    src: "10-qemu-hw-users.rules"
    dest: "/etc/udev/rules.d/10-qemu-hw-users.rules"
    mode: "0644"
  when: pcie_passthrough_enable | bool
