# SPDX-License-Identifier: GPL-2.0
---
name: Setup kdevops
description: Setup kdevops workspace

inputs:
  ci_workflow:
    required: false
    type: string
    default: 'demo'
  dir:
    description: 'Directory'
    required: true
    default: 'workdir'
  kernel_tree:
    required: false
    type: string
    default: 'linux'
  kernel_ref:
    required: false
    type: string
    default: 'master'
  test_mode:
    required: false
    type: string
    default: 'kdevops-ci'

runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        set -euxo pipefail
        git config --global --add safe.directory '*'
        git config --global user.name "kdevops"
        git config --global user.email "kdevops@lists.linux.dev"
        pwd
        ls -lhsta

    - name: Make sure our repo kdevops defconfig exists
      id: defconfig
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
        set -euxo pipefail
        pwd
        ls -lhsta
