---
- name: Verify local build QEMU installation
  command: "which qemu-system-x86_64"
  register: qemu_present
  changed_when: qemu_present.rc == 1
  failed_when: qemu_present.rc != 0 and qemu_present.rc != 1
  tags: ["qemu", "verify"]

- name: Install QEMU build dependencies
  become: true
  become_method: sudo
  dnf:
    name:
      - ImageMagick
      - ImageMagick-libs
      - LibRaw
      - SDL2
      - SDL2-devel
      - SDL2_image
      - SDL2_image-devel
      - alsa-lib-devel
      - at-spi2-atk-devel
      - at-spi2-core-devel
      - atk-devel
      - binutils
      - binutils-gold
      - bison
      - bluez-libs
      - boost-filesystem
      - boost-system
      - boost-thread
      - brlapi
      - brlapi-devel
      - brltty
      - brotli
      - brotli-devel
      - bzip2-devel
      - cairo-devel
      - cairo-gobject-devel
      - capstone
      - capstone-devel
      - cmake-filesystem
      - cpp
      - cyrus-sasl
      - cyrus-sasl-devel
      - daxctl-devel
      - daxctl-libs
      - dbus-devel
      - device-mapper-multipath
      - device-mapper-multipath-devel
      - device-mapper-multipath-libs
      - dyninst
      - elfutils-debuginfod-client-devel
      - elfutils-devel
      - elfutils-libelf-devel
      - emacs-filesystem
      - flex
      - fontawesome-fonts
      - fontconfig-devel
      - freetype-devel
      - fribidi-devel
      - fuse-devel
      - fuse3-devel
      - gc
      - gcc
      - gdk-pixbuf2-devel
      - glib2-devel
      - glib2-static
      - glibc-devel
      - glibc-headers
      - glibc-static
      - glibmm24
      - glusterfs
      - gmp-c++
      - gmp-devel
      - gnutls-c++
      - gnutls-dane
      - gnutls-devel
      - google-roboto-slab-fonts
      - graphite2-devel
      - gtk3-devel
      - guile22
      - harfbuzz-devel
      - harfbuzz-icu
      - imath
      - jasper-libs
      - kernel-devel
      - kernel-headers
      - lato-fonts
      - libX11-devel
      - libXau-devel
      - libXcomposite-devel
      - libXcursor-devel
      - libXdamage-devel
      - libXext-devel
      - libXfixes-devel
      - libXft-devel
      - libXi-devel
      - libXinerama-devel
      - libXrandr-devel
      - libXrender-devel
      - libXtst-devel
      - libacl-devel
      - libaio
      - libaio-devel
      - libattr-devel
      - libblkid-devel
      - libbpf
      - libbpf-devel
      - libcacard
      - libcacard-devel
      - libcap-ng-devel
      - libcloudproviders-devel
      - libconfig
      - libcurl-devel
      - libdatrie-devel
      - libdecor
      - libdrm-devel
      - libepoxy-devel
      - libfdt
      - libfdt-devel
      - libffado
      - libffi-devel
      - libgfapi-devel
      - libgfapi0
      - libgfrpc-devel
      - libgfrpc0
      - libgfxdr-devel
      - libgfxdr0
      - libglusterfs-devel
      - libglusterfs0
      - libglvnd-core-devel
      - libglvnd-devel
      - libglvnd-gles
      - libglvnd-opengl
      - libicu-devel
      - libidn2-devel
      - libiec61883
      - libiscsi
      - libiscsi-devel
      - libjpeg-turbo-devel
      - liblqr-1
      - libmount-devel
      - libmpc
      - libnfs
      - libnfs-devel
      - libpciaccess-devel
      - libpkgconf
      - libpng-devel
      - libraqm
      - libraw1394
      - librdmacm
      - libsamplerate
      - libseccomp-devel
      - libselinux-devel
      - libsepol-devel
      - libsigc++20
      - libslirp
      - libslirp-devel
      - libssh-devel
      - libtasn1-devel
      - libtasn1-tools
      - libthai-devel
      - libtiff-devel
      - libusb1-devel
      - libuuid-devel
      - libwmf-lite
      - libxcb-devel
      - libxcrypt-devel
      - libxcrypt-static
      - libxkbcommon-devel
      - libxml++
      - libxml2-devel
      - libzstd-devel
      - lzo-devel
      - lzo-minilzo
      - m4
      - make
      - man-pages
      - mesa-libEGL-devel
      - mesa-libgbm-devel
      - meson
      - ncurses-c++-libs
      - ncurses-devel
      - nettle-devel
      - ninja-build
      - nspr-devel
      - nss-devel
      - nss-softokn-devel
      - nss-softokn-freebl-devel
      - nss-util-devel
      - openexr-libs
      - openssl-devel
      - p11-kit-devel
      - pam-devel
      - pango-devel
      - pcre-cpp
      - pcre-devel
      - pcre-static
      - pcre-utf16
      - pcre-utf32
      - pcre2-devel
      - pcre2-utf16
      - pcre2-utf32
      - pcsc-lite-devel
      - pcsc-lite-libs
      - perl-Benchmark
      - perl-Test-Harness
      - perl-Text-Unidecode
      - perl-Unicode-EastAsianWidth
      - perl-Unicode-Normalize
      - perl-libintl-perl
      - pixman-devel
      - pkgconf-1.8.0
      - pkgconf-m4
      - pkgconf-pkg-config
      - polkit-libs
      - python3-devel
      - python3-docutils
      - python3-imagesize
      - python3-packaging
      - python3-pip
      - python3-pygments
      - python3-pyparsing
      - python3-snowballstemmer
      - python3-sphinx
      - python3-sphinx-theme-alabaster
      - python3-sphinx_rtd_theme
      - python3-sphinxcontrib-applehelp
      - python3-sphinxcontrib-devhelp
      - python3-sphinxcontrib-htmlhelp
      - python3-sphinxcontrib-jsmath
      - python3-sphinxcontrib-qthelp
      - python3-sphinxcontrib-serializinghtml
      - snappy
      - snappy-devel
      - spice-protocol
      - spice-server
      - spice-server-devel
      - sysprof-capture-devel
      - systemd-devel
      - systemtap
      - systemtap-client
      - systemtap-devel
      - systemtap-runtime
      - systemtap-sdt-devel
      - tbb-2020.3
      - texinfo
      - unzip
      - usbredir
      - usbredir-devel
      - userspace-rcu
      - valgrind
      - valgrind
      - virglrenderer
      - virglrenderer
      - vte-profile
      - vte291
      - vte291
      - wayland-devel
      - xen-devel
      - xen-libs
      - xen-licenses
      - xorg-x11-proto-devel
      - xz-devel
      - yajl
      - zip
      - zlib-devel
      - zlib-static
    state: present
