---
- name: Ensure required /media/ directories are created
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    state: directory
    path: "/media/{{ item }}"
    mode: "0755"
  with_items:
    - scratch
    - "{{ sparsefiles_path }}"
    - test

- name: Pull in the pkg role
  ansible.builtin.include_role:
    name: pkg

- name: Install fstests dependencies on Debian-family guests
  ansible.builtin.import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install fstests dependencies on Suse-family guests
  ansible.builtin.import_tasks: tasks/install-deps/suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'

- name: Install fstests dependencies on RedHat-family guests
  ansible.builtin.import_tasks: tasks/install-deps/redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
