---
- name: Update apt cache accepting release info changes
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
  failed_when: false

- name: Install guestfs dependencies for Debian
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    update_cache: true
    name:
      - libguestfs-tools
      - dhcpcd-base
      - isc-dhcp-client
      - python3-lxml
      - python3-libvirt
      - ovmf
    state: present
