---
- name: Set generic SUSE specific distro facts
  ansible.builtin.set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'
  tags: ["vars"]

- name: Install kdevops generic dependencies
  become: true
  become_method: sudo
  ansible.builtin.package:
    name:
      - gcc
      - make
      - bison
      - flex
      - m4
      - bc
      - sed
      - ncurses-devel
    state: present
  when:
    - is_tumbleweed
