---
# Only run mirror checks for Debian testing (trixie) where mirror issues are common
- name: Extract current APT mirror hostname
  ansible.builtin.shell: |
    grep -E "^deb\s+http" /etc/apt/sources.list | head -1 | awk '{print $2}' | sed 's|http://||' | cut -d'/' -f1
  register: apt_mirror_host
  changed_when: false
  failed_when: false # Connectivity checks may fail gracefully

- name: Check connectivity to current APT mirror
  ansible.builtin.wait_for:
    host: "{{ apt_mirror_host.stdout }}"
    port: 80
    timeout: 10
  register: mirror_connectivity
  failed_when: false # Connectivity checks may fail gracefully
  when: apt_mirror_host.stdout != ""

- name: Display mirror check results
  ansible.builtin.debug:
    msg: |
      Current APT mirror: {{ apt_mirror_host.stdout | default('Not found') }}
      Mirror connectivity: {{ 'OK' if mirror_connectivity is not failed else 'FAILED' }}
  when: apt_mirror_host.stdout != ""

- name: Fall back to official Debian mirrors if current mirror fails
  when:
    - apt_mirror_host.stdout != ""
    - mirror_connectivity is failed
  block:
    - name: Backup current sources.list
      ansible.builtin.copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.backup
        remote_src: true
      become: true

    - name: Apply Debian testing fallback sources
      ansible.builtin.template:
        src: debian-testing-fallback-sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Update APT cache after mirror change
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      become: true

    - name: Inform user about mirror fallback
      ansible.builtin.debug:
        msg: |
          WARNING: The configured APT mirror '{{ apt_mirror_host.stdout }}' is not accessible.
          Falling back to official Debian testing mirrors:
          - deb.debian.org for main packages
          - security.debian.org for security updates

          This may result in slower package downloads depending on your location.
          Consider configuring a local mirror for better performance.
