# SPDX-License-Identifier copyleft-next-0.3.1
---
devconfig_enable_systemd_timesyncd: false
devconfig_enable_systemd_timesyncd_ntp: false
devconfig_enable_systemd_timesyncd_ntp_google: false
devconfig_enable_systemd_timesyncd_ntp_debian: false
devconfig_enable_systemd_timesyncd_ntp_google_debian: false
