---
- name: Install systemd-timesyncd
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: systemd-udev
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  when:
    - devconfig_enable_systemd_timesyncd|bool
  tags: timesyncd
