---
- name: Install libvirt / kvm dependencies
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - qemu-x86
    state: present
  tags: do_install

- name: Enable libvirtd
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    masked: false
  tags: do_deploy

- name: Make sure libvirtd is running
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.systemd:
    state: started
    name: libvirtd
  tags: do_deploy
