---
- name: Set Suse-family distro facts
  ansible.builtin.set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Mark old SLE versions as lacking a python3 junit-xml package
  ansible.builtin.set_fact:
    repos_present: false
  when:
    - is_sle | bool
    - ansible_distribution_major_version in ["10", "11"]

- name: Install python3 junit-xml + pip on the controller (Suse)
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - python3-junit-xml
      - python3-pip
    state: present
  when: repos_present | default(true) | bool
  tags: do_install

- name: Install junitparser via pip on the controller (Suse)
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.pip:
    name:
      - junitparser
  tags: do_install
