---
- name: Get OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Determine which fsprogs package is needed for "{{ nfsd_export_fstype }}"
  ansible.builtin.set_fact:
    fsprogs: "{{ fstype_userspace_progs[nfsd_export_fstype] | default() }}"

- name: Add {{ fsprogs }} to the nfsd packages list
  ansible.builtin.set_fact:
    nfsd_packages: "{{ nfsd_packages + [fsprogs] }}"
  when:
    - fsprogs is defined
    - fsprogs | length > 0

- name: Add gssproxy to the nfsd packages list
  ansible.builtin.set_fact:
    nfsd_packages: "{{ nfsd_packages + ['gssproxy'] }}"
  when: kdevops_krb5_enable|bool

- name: Install nfsd dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name: "{{ nfsd_packages }}"
    state: present
    update_cache: true
  tags: ["pynfs", "deps"]
