# SPDX-License-Identifier: GPL-2.0
---
name: Simple Setup
description: Simple setup with working directory using run_id

inputs:
  ci_workflow:
    required: true
    type: string
    default: 'blktests_nvme'
  work_dir:
    description: 'Working directory (should include run_id)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create working directory
      shell: bash
      run: |
        set -euxo pipefail
        echo "Working directory: ${{ inputs.work_dir }}"
        echo "CI workflow: ${{ inputs.ci_workflow }}"
        echo "GitHub run ID: ${{ github.run_id }}"
        
        # Clean up any existing directory
        rm -rf "${{ inputs.work_dir }}" || true
        
        # Create the working directory
        mkdir -p "${{ inputs.work_dir }}/kdevops"
        
        # Copy kdevops source to working directory
        cp -r ${{ github.workspace }}/* "${{ inputs.work_dir }}/kdevops/" || true
        cp -r ${{ github.workspace }}/.* "${{ inputs.work_dir }}/kdevops/" 2>/dev/null || true
        
        ls -la "${{ inputs.work_dir }}/kdevops/"

    - name: Basic git configuration
      shell: bash
      run: |
        set -euxo pipefail
        git config --global --add safe.directory '*'
        git config --global user.name "kdevops-simple"
        git config --global user.email "kdevops@example.com"

    - name: Check defconfig exists
      shell: bash
      working-directory: ${{ inputs.work_dir }}/kdevops
      run: |
        set -euxo pipefail
        echo "Checking for defconfig: ${{ inputs.ci_workflow }}"
        
        if [[ -f "defconfigs/${{ inputs.ci_workflow }}" ]]; then
          echo "✓ Found defconfig: defconfigs/${{ inputs.ci_workflow }}"
        else
          echo "✗ Missing defconfig: defconfigs/${{ inputs.ci_workflow }}"
          echo "Available defconfigs:"
          ls -1 defconfigs/ | head -10
          exit 1
        fi

    - name: Simple defconfig setup
      shell: bash  
      working-directory: ${{ inputs.work_dir }}/kdevops
      run: |
        set -euxo pipefail
        echo "Setting up simple configuration..."
        
        # Use a simple host prefix with run_id
        HOST_PREFIX="simple-${{ github.run_id }}"
        echo "Host prefix: $HOST_PREFIX"
        
        # Try to run defconfig
        make "KDEVOPS_HOSTS_PREFIX=$HOST_PREFIX" "defconfig-${{ inputs.ci_workflow }}" || {
          echo "Defconfig failed, listing available configs..."
          ls -la defconfigs/
          exit 1
        }
        
        echo "✓ Configuration completed successfully"