---
- name: Install guestfs dependencies for CentOS
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.dnf:
    update_cache: true
    name:
      - guestfs-tools
      - dhcpcd
    state: present
  when:
    - ansible_facts['distribution']|lower == 'centos'

- name: Install guestfs dependencies for Red Hat Enterprise (non-CentOS)
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    update_cache: true
    name:
      - libguestfs-tools
      - dhcpcd
    state: present
  when:
    - ansible_distribution != "Fedora"
    - ansible_facts['distribution']|lower != 'centos'
