---
- name: Install libvirt / kvm dependencies
  become: true
  become_method: sudo
  ansible.builtin.package:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - qemu-x86
    state: present

- name: Enable libvirtd
  become: true
  become_method: sudo
  systemd:
    name: libvirtd
    enabled: true
    masked: false

- name: Make sure libvirtd is running
  become: true
  become_method: sudo
  systemd:
    state: started
    name: libvirtd
