---
# Collect monitoring data WITHOUT stopping monitoring services
# This allows peeking at intermediate results during long-running tests

# Import common monitoring setup tasks
- ansible.builtin.import_tasks: common/setup.yml
  when:
    - enable_monitoring|default(false)|bool

# Import folio migration interim collection tasks
- ansible.builtin.import_tasks: monitors/folio_migration/collect_only.yml
  when:
    - monitor_developmental_stats|default(false)|bool
    - monitor_folio_migration|default(false)|bool

# Display comprehensive interim monitoring collection summary
- name: Display interim monitoring collection summary
  ansible.builtin.debug:
    msg: |
      Interim monitoring data collection complete (monitoring still running).
      Results available in: {{ monitoring_results_path }}
      {% if monitor_developmental_stats|default(false)|bool and monitor_folio_migration|default(false)|bool %}
      - Folio migration interim data collected
      {% endif %}
      {% if localhost_matplotlib_check is defined and localhost_matplotlib_check.rc is defined and localhost_matplotlib_check.rc == 0 %}
      Plot generation status:
      {% if folio_interim_plot_generation is defined and folio_interim_plot_generation.rc is defined and folio_interim_plot_generation.rc == 0 %}
      - Folio migration interim plots generated
      {% endif %}
      {% else %}
      Plot generation skipped - matplotlib not available on localhost
      {% endif %}
  run_once: true
  when:
    - enable_monitoring|default(false)|bool
