---
# Monitoring orchestrator - includes individual collection modules

# Import common monitoring setup tasks
- ansible.builtin.import_tasks: common/setup.yml
  when:
    - monitor_developmental_stats|default(false)|bool
    - (monitor_folio_migration|default(false)|bool)

# Import folio migration collection tasks
- ansible.builtin.import_tasks: monitors/folio_migration/collect.yml
  when:
    - monitor_developmental_stats|default(false)|bool
    - monitor_folio_migration|default(false)|bool