---
# Collect monitoring data WITHOUT stopping monitoring services
# This allows peeking at intermediate results during long-running tests

# Import common monitoring setup tasks
- ansible.builtin.import_tasks: common/setup.yml
  when:
    - enable_monitoring|default(false)|bool

# Import folio migration interim collection tasks
- ansible.builtin.import_tasks: monitors/folio_migration/collect_only.yml
  when:
    - monitor_developmental_stats|default(false)|bool
    - monitor_folio_migration|default(false)|bool

# Import NVMe SMART log interim collection tasks
- ansible.builtin.import_tasks: monitors/nvme_smart_log/collect_only.yml
  when:
    - monitor_nvme_smart_log|default(false)|bool

# Generate plots from interim data on localhost
- name: Check if matplotlib is available on localhost
  ansible.builtin.command: python3 -c "import matplotlib.pyplot"
  delegate_to: localhost
  register: localhost_matplotlib_check
  ignore_errors: true
  run_once: true
  when:
    - enable_monitoring|default(false)|bool

- name: Find interim monitoring data files for plotting
  ansible.builtin.find:
    paths: "{{ monitoring_results_path }}"
    patterns: "*_interim.txt"
  delegate_to: localhost
  register: interim_monitoring_files
  run_once: true
  when:
    - enable_monitoring|default(false)|bool
    - localhost_matplotlib_check.rc == 0

- name: Generate folio migration interim plots on localhost
  ansible.builtin.command: |
    python3 {{ playbook_dir }}/roles/monitoring/files/plot_folio_migration_stats.py
      -o {{ monitoring_results_path }}/interim_folio_migration_plot.png
      {{ interim_monitoring_files.files | selectattr('path', 'match', '.*folio_migration.*') | map(attribute='path') | join(' ') }}
  delegate_to: localhost
  register: folio_interim_plot_generation
  ignore_errors: true
  run_once: true
  when:
    - enable_monitoring|default(false)|bool
    - localhost_matplotlib_check.rc == 0
    - interim_monitoring_files.files | selectattr('path', 'match', '.*folio_migration.*') | list | length > 0

- name: Generate NVMe SMART log interim plots on localhost
  ansible.builtin.command: |
    python3 {{ playbook_dir }}/roles/monitoring/files/plot_nvme_smart_stats.py
      -o {{ monitoring_results_path }}/interim_nvme_smart_plot.png
      {{ interim_monitoring_files.files | selectattr('path', 'match', '.*nvme_smart_log.*') | map(attribute='path') | join(' ') }}
  delegate_to: localhost
  register: nvme_interim_plot_generation
  ignore_errors: true
  run_once: true
  when:
    - enable_monitoring|default(false)|bool
    - localhost_matplotlib_check.rc == 0
    - interim_monitoring_files.files | selectattr('path', 'match', '.*nvme_smart_log.*') | list | length > 0

# Display comprehensive interim monitoring collection summary
- name: Display interim monitoring collection summary
  ansible.builtin.debug:
    msg: |
      Interim monitoring data collection complete (monitoring still running).
      Results available in: {{ monitoring_results_path }}
      {% if monitor_developmental_stats|default(false)|bool and monitor_folio_migration|default(false)|bool %}
      - Folio migration interim data collected
      {% endif %}
      {% if monitor_nvme_smart_log|default(false)|bool %}
      - NVMe SMART log interim data collected
      {% endif %}
      {% if localhost_matplotlib_check is defined and localhost_matplotlib_check.rc is defined and localhost_matplotlib_check.rc == 0 %}
      Plot generation status:
      {% if folio_interim_plot_generation is defined and folio_interim_plot_generation.rc is defined and folio_interim_plot_generation.rc == 0 %}
      - Folio migration interim plots generated
      {% endif %}
      {% if nvme_interim_plot_generation is defined and nvme_interim_plot_generation.rc is defined and nvme_interim_plot_generation.rc == 0 %}
      - NVMe SMART log interim plots generated
      {% endif %}
      {% else %}
      Plot generation skipped - matplotlib not available on localhost
      {% endif %}
  run_once: true
  when:
    - enable_monitoring|default(false)|bool
