---
# Monitoring orchestrator - includes individual monitor modules

# Import folio migration monitoring tasks
- ansible.builtin.import_tasks: monitors/folio_migration/run.yml
  when:
    - monitor_developmental_stats|default(false)|bool
    - monitor_folio_migration|default(false)|bool