---
- name: Run the folio_migration sub-role (start phase)
  ansible.builtin.include_role:
    name: monitoring/monitors/folio_migration
    tasks_from: run
  when:
    - monitor_developmental_stats | default(false) | bool
    - monitor_folio_migration | default(false) | bool
  tags: [monitor_folio_migration]

- name: Run the memory_fragmentation sub-role (start phase)
  ansible.builtin.include_role:
    name: monitoring/monitors/memory_fragmentation
    tasks_from: run
  when:
    - monitor_developmental_stats | default(false) | bool
    - monitor_memory_fragmentation | default(false) | bool
  tags: [monitor_memory_fragmentation]
