---
- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true
  tags: linux

- name: Install nvme tools
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - nvme-cli
    update_cache: true

- name: Install blktests build dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - bison
      - flex
      - git
      - automake
      - libuuid1
      - quota
      - make
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
      - gawk
      - uuid-runtime
      - acl
      - bc
      - dump
      - indent
      - libtool
      - lvm2
      - psmisc
      - sed
      - libacl1
      - libacl1-dev
      - "{{ pkg_libaio }}"
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - fio
      - libcap2-bin
      - libtool
      - gcc
      - git
      - nbd-server
      - nbd-client
      - multipath-tools
      - libaio-dev
      - g++
      - parted
      - libnl-utils
      - zlib1g-dev
    state: present
    update_cache: true
  tags: ["blktests", "deps"]
