---
- name: Install systemd-timesyncd
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - systemd-timesyncd
    state: present
  when:
    - devconfig_enable_systemd_timesyncd|bool
  tags: timesyncd
