ifeq (y,$(CONFIG_SELFTESTS_SECTION_VMA))
SELFTESTS_HELP_TARGETS += selftests-help-menu-target-vma
selftests-vma:
	$(Q)$(MAKE) selftests-baseline HOSTS=$(KDEVOPS_HOSTS_PREFIX)-vma
endif

selftests-help-menu-target-vma:
	@echo "selftests-vma                     - Runs selftests for VMA userspace tests"
