---
- name: Set generic SUSE specific distro facts
  ansible.builtin.set_fact:
    blktests_is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    blktests_is_leap: '{{ "Leap" in ansible_distribution }}'
    blktests_is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Set SLE specific version labels to make checks easier
  ansible.builtin.set_fact:
    blktests_is_sle10: '{{ ansible_distribution_major_version == "10" }}'
    blktests_is_sle11: '{{ ansible_distribution_major_version == "11" }}'
    blktests_is_sle12: '{{ ansible_distribution_major_version == "12" }}'
    blktests_is_sle15: '{{ ansible_distribution_major_version == "15" }}'
    blktests_is_sle10sp3: '{{ ansible_distribution_version == "10.3" }}'
    blktests_is_sle11sp1: '{{ ansible_distribution_version == "11.1" }}'
    blktests_is_sle11sp4: '{{ ansible_distribution_version == "11.4" }}'
    blktests_is_sle12sp1: '{{ ansible_distribution_version == "12.1" }}'
    blktests_is_sle12sp3: '{{ ansible_distribution_version == "12.3" }}'
    blktests_is_sle12sp5: '{{ ansible_distribution_version == "12.5" }}'
    blktests_is_sle15sp2: '{{ ansible_distribution_version == "15.2" }}'
    blktests_is_sle15sp3: '{{ ansible_distribution_version == "15.3" }}'
    blktests_is_sle15sp4: '{{ ansible_distribution_version == "15.4" }}'
  when:
    - blktests_is_sle|bool

- name: Set SLE specific version labels to make checks easier when not SLE
  ansible.builtin.set_fact:
    blktests_is_sle10: false
    blktests_is_sle11: false
    blktests_is_sle12: false
    blktests_is_sle12sp5: false
    blktests_is_sle15: false
    blktests_is_sle10sp3: false
    blktests_is_sle11sp1: false
    blktests_is_sle11sp4: false
    blktests_is_sle12sp1: false
    blktests_is_sle12sp3: false
    blktests_is_sle15sp2: false
    blktests_is_sle15sp3: false
    blktests_is_sle15sp4: false
  when:
    - not blktests_is_sle|bool

- name: By default we assume we have figured out how to add repos on a release
  ansible.builtin.set_fact:
    blktests_repos_present: true

- name: Lets us disable things which require a zypper repo present
  ansible.builtin.set_fact:
    blktests_repos_present: false
  when:
    - blktests_is_sle|bool
    - blktests_is_sle10|bool or blktests_is_sle11|bool

- name: The default is to assume all distros supports nvme-utils
  ansible.builtin.set_fact:
    blktests_lacks_nvme_utils: false

- name: Does this release lack nvme-utils
  ansible.builtin.set_fact:
    blktests_lacks_nvme_utils: true
  when:
    - blktests_is_sle|bool
    - blktests_is_sle10|bool or blktests_is_sle11|bool or blktests_is_sle12sp1|bool

- name: Install NVMe tools
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - nvme-cli
    state: present
  when:
    - blktests_repos_present|bool
    - not blktests_lacks_nvme_utils|bool

- name: Install build dependencies for blktests
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - bison
      - flex
      - git-core
      - automake
      - gcc
      - libuuid1
      - libuuid-devel
      - quota
      - make
      - xfsprogs
      - xfsprogs-devel
      - e2fsprogs
      - btrfsprogs
      - gawk
      - util-linux
      - uuidd
      - acl
      - bc
      - dump
      - libtool
      - lvm2
      - psmisc
      - sed
      - libacl1
      - libacl-devel
      - libaio1
      - libaio-devel
      - attr
      - libattr-devel
      - openssl-devel
      - libcap-progs
      - fio
      - multipath-tools
      - gcc-c++
      - parted
      - libnl-config
    state: present
  when:
    - blktests_repos_present|bool

- name: Install tumblweed packages
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - libgdbm6
      - dbench
    state: present
  when:
    - blktests_is_tumbleweed|bool

- name: Install leap packages
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - libgdbm4
      - dbench
      - dbench4
    state: present
  when:
    - blktests_is_tumbleweed|bool

- name: Install libgdbm4
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - libgdbm4
    state: present
  when:
    - blktests_is_sle15sp2|bool or blktests_is_sle15sp3|bool or sle15sp4|bool

# If we ever upgrade the git for nbd we'll need
# to find way to get autoconf-archive for sles15sp4
# as it is required...
- name: Install autoconf-archive for building nbd
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - autoconf-archive
    state: present
  when:
    - not sle15sp4|bool
    - blktests_is_sle15sp2|bool or blktests_is_sle15sp3|bool

- name: The default is to assume we do not want to add the benchmark repo
  ansible.builtin.set_fact:
    blktests_add_benchmark_repo: false

- name: Does this release require the benchmark repo
  ansible.builtin.set_fact:
    blktests_add_benchmark_repo: true
  when:
    - blktests_is_sle15sp2|bool or blktests_is_sle15sp3|bool or blktests_is_sle15sp4|bool or blktests_is_sle12sp5|bool

- name: Add benchmark sles12sp5 opensuse repo when needed
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.script:
    cmd: "{{ role_path }}/scripts/add-suse-repo-if-not-found.sh http://download.opensuse.org/repositories/benchmark/SLE_12_SP5/ benchmark benchmark"
  when:
    - blktests_is_sle12sp5|bool

- name: Add benchmark sles15sp2 opensuse repo when needed
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.script:
    cmd: "{{ role_path }}/scripts/add-suse-repo-if-not-found.sh http://download.opensuse.org/repositories/benchmark/SLE_15_SP2/ benchmark benchmark"
  when:
    - blktests_is_sle15sp2|bool

- name: Add benchmark sles15sp3 opensuse repo when needed
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.script:
    cmd: "{{ role_path }}/scripts/add-suse-repo-if-not-found.sh http://download.opensuse.org/repositories/benchmark/SLE_15_SP3/ benchmark benchmark"
  when:
    - blktests_is_sle15sp3|bool or blktests_is_sle15sp4|bool

- name: Install dbench when needed
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - dbench
    state: present
  when:
    - blktests_add_benchmark_repo|bool

- name: The default is to assume we do not want to to compile nbd manually
  ansible.builtin.set_fact:
    blktests_compile_nbd: false

- name: Set when we need to compile nbd
  ansible.builtin.set_fact:
    blktests_compile_nbd: true
  when:
    - blktests_is_sle15sp2|bool or blktests_is_sle15sp3|bool or blktests_is_sle15sp4|bool or blktests_is_leap|bool

- name: Install build dependencies for nbd
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - glib2-devel
    state: present
  when:
    - blktests_repos_present|bool
    - blktests_compile_nbd|bool

- name: Git clone nbd
  ansible.builtin.git:
    repo: "{{ nbd_git }}"
    dest: "{{ nbd_data }}"
    update: true
    version: "{{ nbd_version }}"
  when:
    - blktests_repos_present|bool
    - blktests_compile_nbd|bool
  tags: ["git", "blktests", "nbd"]

- name: Skip documentation for nbd as we lack the requirement of docbook2man
  ansible.builtin.file:
    path: "{{ nbd_data }}/man/{{ item }}"
    state: touch
    mode: "0644"
  with_items:
    - "nbd-client.8.sh.in"
    - "nbd-server.5.sh.in"
    - "nbd-server.1.sh.in"
    - "nbd-trdump.1.sh.in"
    - "nbdtab.5.sh.in"
  loop_control:
    label: "Faking generation of documentation for nbd{{ item }}"
  tags: ["blktests", "nbd"]
  when:
    - blktests_repos_present|bool
    - blktests_compile_nbd|bool

- name: Run autogen for nbd
  ansible.builtin.command: "./autogen.sh"
  tags: ["blktests", "nbd"]
  args:
    chdir: "{{ nbd_data }}"
  changed_when: true

- name: Run configure for nbd
  ansible.builtin.command: "./configure"
  tags: ["blktests", "nbd"]
  args:
    chdir: "{{ nbd_data }}"
  changed_when: true

- name: Get blktests_nproc
  ansible.builtin.command: "{{ num_jobs }}"
  tags: ["git", "blktests", "nbd"]
  register: blktests_nproc
  changed_when: false

- name: Build nbd
  tags: ["git", "blktests", "nbd"]
  community.general.make:
    chdir: "{{ nbd_data }}"
    jobs: "{{ blktests_nproc.stdout }}"

- name: Install nbd
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  ansible.builtin.command: "{{  make }} install"
  tags: ["git", "blktests", "nbd"]
  args:
    chdir: "{{ nbd_data }}"
  changed_when: true
