---
- name: Set QEMU system package based on architecture
  set_fact:
    qemu_system_package: >-
      {{
        'qemu-system-aarch64' if (ansible_architecture == 'aarch64' or target_arch_arm64|default(false)|bool)
        else 'qemu-system-x86'
      }}

- name: Install libvirt / kvm dependencies
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - "{{ qemu_system_package }}"
    state: present

- name: Enable libvirtd
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    masked: false

- name: Make sure libvirtd is running
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    state: started
    name: libvirtd
