---
- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: linux

- name: Install ndctl build deps
  become: true
  become_method: sudo
  apt:
    name:
      - git
      - meson
      - gcc
      - pkg-config
      - cmake
      - libkmod-dev
      - libudev-dev
      - uuid-dev
      - libjson-c-dev
      - asciidoctor
      - libkeyutils-dev
      - libiniparser-dev
      - bash-completion
      - jq
      - libtraceevent-dev
      - libtracefs-dev
    state: present
    update_cache: true
  tags: ["cxl", "deps"]
