---
- name: Install btrfs-progs build dependencies
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name:
      - e2fsprogs-devel
      - libblkid-devel
      - libuuid-devel
      - libzstd-devel
      - systemd-devel
      - lzo-devel
    state: present
