---
- name: Allow for distro source change / upgrade
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.command: "apt-get update  --allow-releaseinfo-change"
  register: release_info_changed
  changed_when: "release_info_changed.rc == 0"
  args:
    warn: false
  tags: ["apt", "release-info-change"]
  when:
    - devconfig_try_upgrade|bool

- name: Update apt cache and do dist-upgrade
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  tags: ["apt", "cache"]
  when:
    - devconfig_try_upgrade|bool

- name: Reboot system to make the new kernel and modules take effect
  become: true
  become_method: sudo
  ansible.builtin.reboot:
  when:
    - devconfig_try_upgrade|bool
