---
- name: Install kdc dependencies
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - krb5-server
      - krb5-libs
      - krb5-workstation
