---
- name: Adds the user to the respective distro libvirt groups
  become: yes
  become_method: sudo
  user:
    name: "{{ running_user }}"
    groups: libvirt,kvm,libvirt-qemu
    append: yes
  when:
    - not libvirt_session
    - not only_verify_user|bool
  tags: [ 'build-deps' ]

- name: Check if apparmor_status exists
  stat:
    path: /usr/sbin/apparmor_status
  register: apparmor_file_stat_result
  when: 'only_verify_user|bool'
  tags: [ 'build-deps' ]

- name: Verify if AppArmor is disabled when applicable
  become: yes
  become_method: sudo
  command:
    cmd: /usr/sbin/apparmor_status --enabled
  register: apparmor_check
  failed_when: apparmor_check.rc == 0
  when:
    - 'only_verify_user|bool'
    - 'apparmor_file_stat_result.stat.exists'
  tags: [ 'build-deps' ]

- name: Verifies user's effective group allows to run libvirt/kvm without being root
  shell: groups | grep {{ item }}
  with_items:
    - libvirt
    - kvm
    - libvirt-qemu
  loop_control:
    label: "Verifying if user's current effective groups includes {{ item }}"
  register: group_check
  failed_when: False
  ignore_errors: true
  when:
    - not libvirt_session
    - not only_verify_user|bool
  tags: [ 'build-deps' ]

- name: Ensure our user is part of the libvirt/kvm groups
  tags: [ 'journal', 'build-deps' ]
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name:  "{{ ansible_user_id }}"
    groups:
      - libvirt
      - kvm
      - libvirt-qemu
    append: yes
  when:
    - not libvirt_session
    - not only_verify_user|bool
