---
- name: Debian-specific set up
  ansible.builtin.include_tasks: install-deps/debian/main.yml
  when: ansible_os_family == 'Debian'
  tags: [ 'build-deps' ]

- name: SuSE-specific set up
  ansible.builtin.include_tasks: install-deps/suse/main.yml
  when: ansible_os_family == 'Suse'
  tags: [ 'build-deps' ]

- name: Red Hat-specific set up
  ansible.builtin.include_tasks: install-deps/redhat/main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] != "Fedora"
  tags: [ 'build-deps' ]

- name: Fedora-specific set up
  ansible.builtin.include_tasks: install-deps/fedora/main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] == "Fedora"
  tags: [ 'build-deps' ]
