---
- name: Debian user enablement
  ansible.builtin.include_tasks: enable-user/debian/main.yml
  when: ansible_os_family == 'Debian'

- name: SuSE user enablement
  ansible.builtin.include_tasks: enable-user/suse/main.yml
  when: ansible_os_family == 'Suse'

- name: Red Hat user enablement
  ansible.builtin.include_tasks: enable-user/redhat/main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] != "Fedora"

- name: Fedora user enablement
  ansible.builtin.include_tasks: enable-user/fedora/main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts['distribution'] == "Fedora"
