# SPDX-License-Identifier GPL-2.0+
---
kdevops_terraform_ssh_config_update: false
kdevops_terraform_ssh_config_update_strict: false
kdevops_terraform_ssh_config_update_backup: false

kdevops_terraform_provider: "aws"
kdevops_terraform_ssh_pubkey_file: "/dev/null"
kdevops_terraform_ssh_user: "nully"
kdevops_terraform_ssh_file: "/dev/null"

kdevops_terraform_tfvars_template: "/dev/null"
kdevops_terraform_tfvars_template_full_path: "/dev/null"
kdevops_terraform_tfvars: "terraform/terraform.tfvars"

terraform_private_net_enabled: "false"
terraform_private_net_prefix: ""
terraform_private_net_mask: 0

terraform_oci_assign_public_ip: false
terraform_oci_use_existing_vcn: false

terraform_openstack_cloud_name: "invalid"
terraform_openstack_instance_prefix: "invalid"
terraform_openstack_flavor: "invalid"
terraform_openstack_image_name: "invalid"
terraform_openstack_ssh_pubkey_name: "invalid"
