---
- name: Pull in the pkg role
  ansible.builtin.include_role:
    name: pkg

- name: Install blktests dependencies on Debian-family guests
  ansible.builtin.import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install blktests dependencies on Suse-family guests
  ansible.builtin.import_tasks: tasks/install-deps/suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'

- name: Install blktests dependencies on RedHat-family guests
  ansible.builtin.import_tasks: tasks/install-deps/redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
