---
- name: Update apt cache
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: true
  tags: linux

- name: Force dbench compilation on Debian
  ansible.builtin.set_fact:
    compile_dbench: false

- name: Install dbench build dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - git
      - automake
      - autoconf
      - gcc
      - libuuid1
      - quota
      - make
      - sed
      - libacl1
      - libacl1-dev
      - "{{ pkg_libaio }}"
      - libaio-dev
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - libcap2-bin
      - libtool
      - pkg-config
      - libpopt-dev
      - libtirpc-dev
      - libtirpc3
      - xsltproc
      - libsmbclient-dev
      - libiscsi-dev
    state: present
    update_cache: true
  tags: ["dbench", "deps"]
