---
- name: Install kdevops generic dependencies
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name:
      - bison
      - flex
      - make
      - bc
      - sed
      - screen
      - python3
      - ncurses-devel
    state: present
