---
- name: Gather the list of running libvirt guests
  run_once: true
  community.libvirt.virt:
    ansible.builtin.command: list_vms
    state: running
    uri: "{{ libvirt_uri }}"
  register: running_vms

- name: Shut down each running target node
  community.libvirt.virt:
    name: "{{ inventory_hostname }}"
    ansible.builtin.command: destroy
    uri: "{{ libvirt_uri }}"
  changed_when: true
  when:
    - inventory_hostname in running_vms.list_vms

- name: Gather the list of stopped libvirt guests
  run_once: true
  community.libvirt.virt:
    ansible.builtin.command: list_vms
    state: shutdown
    uri: "{{ libvirt_uri }}"
  register: shutdown_vms

- name: Undefine each stopped target node
  community.libvirt.virt:
    ansible.builtin.command: "undefine"
    flags:
      - "nvram"
      - "snapshots_metadata"
      - "checkpoints_metadata"
    name: "{{ inventory_hostname }}"
    uri: "{{ libvirt_uri }}"
  changed_when: true
  when:
    - inventory_hostname in shutdown_vms.list_vms
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Clean up storage volumes for target nodes
  ansible.builtin.shell: |
    virsh -c {{ libvirt_uri }} vol-delete --pool {{ kdevops_storage_pool_path }} {{ inventory_hostname }}/root.raw 2>/dev/null || true
    virsh -c {{ libvirt_uri }} vol-delete --pool {{ kdevops_storage_pool_path }} {{ inventory_hostname }}.raw 2>/dev/null || true
  changed_when: false
  # TODO: Review - was ignore_errors: true
  failed_when: false  # Always succeed - review this condition

- name: Remove per-node configuration files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ guestfs_path }}/{{ inventory_hostname }}"
    - "{{ kdevops_storage_pool_path }}/guestfs/{{ inventory_hostname }}"

- name: Remove global configuration files
  run_once: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ kdevops_ssh_config }}"
    - "{{ topdir_path }}/{{ kdevops_nodes }}"
