---
kdevops_archive_data_count: 0
kdevops_results: "{{ topdir_path }}/archive"
kdevops_results_local: "{{ kdevops_results }}/{{ target_linux_ref }}/"
kdevops_results_repo_url_user: "git"
kdevops_results_repo_url: "{{ kdevops_results_repo_url_user}}@github.com:linux-kdevops/kdevops-results-archive.git"
kdevops_results_repo_url_demo: "{{ kdevops_results_repo_url_user}}@github.com:linux-kdevops/kdevops-results-archive-demo.git"
kdevops_results_repo_path: "{{ kdevops_results_repo_url.split('@')[1] }}"
kdevops_results_name: "{{ kdevops_results_repo_path.split('/')[-1] | regex_replace('\\.git$', '') }}"
kdevops_results_archive_dir: "{{ topdir_path }}/../{{ kdevops_results_name }}"
kdevops_archive_mirror_present: false
kdevops_archive_host: "{{ kdevops_results_repo_path.split(':')[0] }}"
kdevops_archive: "/mirror/{{ kdevops_results_name }}.git"
kdevops_archive_demo: false
bootlinux_tree_set_by_cli: false
kdevops_archive_base: "selftests/gh/linux-modules-kpd/20241021"
kdevops_archive_test_number: "0001"
kdevops_archive_prefix: "{{ kdevops_archive_base }}/{{ kdevops_archive_test_number }}/v6.12-rc4/"
kdevops_archive_test_trigger: "linux-radix-tree-kbd"
kdevops_archive_test_subject: "maple_tree: dump error message based on format"
kdevops_archive_ci_subject_patchform_name: "maple_tree-dump-error-message-based-on-format"
kdevops_archive_ci_test_result: "unknown"
kdevops_archive_test_commit: "Elaborate here on test details."
kdevops_archive_test_ref: "{{ target_linux_ref }}"
