# SPDX-License-Identifier copyleft-next-0.3.1
---
create_partition_disk_device: "/dev/some-block-device"
create_partition_disk_fstype: "xfs"
# For instance use nofail if you want your bootup to work
# even if mount did not succeed.
create_partition_disk_mount_opts: "defaults"
create_partition_disk_label: "data"
create_partition_disk_fs_opts: "-L {{ create_partition_disk_label }}"
create_partition_disk_path: "/data"
create_partition_disk_user: "root"
create_partition_disk_group: "root"
create_partition_disk_mode: "u=rwx,g=rwx,o=rwxt"
create_partition_disk_env: {}
