---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install systemd-timesyncd
  include_tasks: install-deps/main.yml

- name: Set up the server /etc/systemd/timesyncd.conf
  tags: ["timesyncd"]
  become: true
  become_flags: "su - -c"
  become_method: sudo
  template:
    src: "timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf"
    force: true
    trim_blocks: true
    lstrip_blocks: true
  when:
    - devconfig_enable_systemd_timesyncd|bool

- name: Enable NTP
  become: true
  become_flags: "su - -c"
  become_method: sudo
  command: "timedatectl set-ntp true"
  when:
    - devconfig_enable_systemd_timesyncd_ntp|bool

- name: Restart systemd-timesyncd.service on the server
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    daemon_reload: true
    enabled: true
    state: restarted
  when:
    - devconfig_enable_systemd_timesyncd|bool

- name: Ensure systemd-timesyncd.service is running on the server
  become: true
  become_flags: "su - -c"
  become_method: sudo
  command: "timedatectl status"
  when:
    - devconfig_enable_systemd_timesyncd|bool
