---
- name: Set generic SUSE specific distro facts
  ansible.builtin.set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Set SLE specific version labels to make checks easier
  ansible.builtin.set_fact:
    is_sle10: '{{ ansible_distribution_major_version == "10" }}'
    is_sle11: '{{ ansible_distribution_major_version == "11" }}'
    is_sle12: '{{ ansible_distribution_major_version == "12" }}'
    is_sle15: '{{ ansible_distribution_major_version == "15" }}'
    is_sle10sp3: '{{ ansible_distribution_version == "10.3" }}'
    is_sle11sp1: '{{ ansible_distribution_version == "11.1" }}'
    is_sle11sp4: '{{ ansible_distribution_version == "11.4" }}'
    is_sle12sp1: '{{ ansible_distribution_version == "12.1" }}'
    is_sle12sp3: '{{ ansible_distribution_version == "12.3" }}'
    is_sle12sp5: '{{ ansible_distribution_version == "12.5" }}'
    is_sle15sp2: '{{ ansible_distribution_version == "15.2" }}'
    is_sle15sp3: '{{ ansible_distribution_version == "15.3" }}'
    is_sle15sp4: '{{ ansible_distribution_version == "15.4" }}'
  when:
    - is_sle|bool

- name: Set SLE specific version labels to make checks easier when not SLE
  ansible.builtin.set_fact:
    is_sle10: false
    is_sle11: false
    is_sle12: false
    is_sle15: false
    is_sle10sp3: false
    is_sle11sp1: false
    is_sle11sp4: false
    is_sle12sp1: false
    is_sle12sp3: false
    is_sle12sp5: false
    is_sle15sp2: false
    is_sle15sp3: false
    is_sle15sp4: false
  when:
    - not is_sle|bool

- name: By default we assume we have figured out how to add repos on a release
  ansible.builtin.set_fact:
    repos_present: true

- name: Lets us disable things which require a zypper repo present
  ansible.builtin.set_fact:
    repos_present: false
  when:
    - is_sle|bool
    - is_sle10|bool or is_sle11|bool

- name: Install build dependencies for ndctl
  become: true
  become_method: sudo
  community.general.zypper:
    name:
      - git-core
      - meson
      - gcc
      - pkg-config
      - libuuid1
      - libuuid-devel
      - cmake
      - libkmod-devel
      - libudev-devel
      - libuuid-devel
      - uuid-devel
      - libjson-c-devel
      - ruby3.1-rubygem-asciidoctor
      - keyutils-devel
      - libiniparser-devel
      - bash-completion-devel
      - jq
      - libtraceevent-devel
      - libtracefs-devel
    state: present
    replacefiles: true
  when:
    - repos_present|bool
