---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true

- name: Check if PCI-E sysfs driver_override file exists
  become: true
  become_flags: "su - -c"
  become_method: sudo
  vars:
    sysfs_override: "{{ pcie_sysfs_device_path_prefix }}/{{ item.pcie_id}}/driver_override"
  ansible.builtin.stat:
    path: "{{ sysfs_override }}"
  with_items: "{{ pcie_passthrough_devices }}"
  loop_control:
    label: "Checking if {{ sysfs_override }} exists for {{ item.pcie_human_name }} ..."
  register: sysfs_driver_override_file_stats
  when:
    - pcie_passthrough_enable|bool

- name: Enable libvirt to use PCI-E sysfs driver_override file
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    group: "{{ libvirt_qemu_group }}"
    mode: "0664"
  with_items: "{{ sysfs_driver_override_file_stats.results }}"
  loop_control:
    label: "Setting permissions for {{ item.stat.path }} ..."
  when:
    - pcie_passthrough_enable|bool
    - item.stat.exists

- name: Check if PCI-E sysfs unbind file exists
  become: true
  become_flags: "su - -c"
  become_method: sudo
  vars:
    sysfs_unbind: "{{ pcie_sysfs_device_path_prefix }}/{{ item.pcie_id}}/unbind"
  ansible.builtin.stat:
    path: "{{ sysfs_unbind }}"
  with_items: "{{ pcie_passthrough_devices }}"
  loop_control:
    label: "Checking if {{ sysfs_unbind }} exists for {{ item.pcie_human_name }} ..."
  register: sysfs_driver_unbind_file_stats
  when:
    - pcie_passthrough_enable|bool

- name: Enable libvirt to use PCI-E sysfs unbind file
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    group: "{{ libvirt_qemu_group }}"
    mode: "0220"
  with_items: "{{ sysfs_driver_unbind_file_stats.results }}"
  loop_control:
    label: "Setting permissions for sysfs unbind file"
  when:
    - pcie_passthrough_enable|bool
    - item.stat.exists

- name: Deploy udev 10-qemu-hw-users.rules which enables libvirt to use vfio subsystem
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: "10-qemu-hw-users.rules"
    dest: "/etc/udev/rules.d/"
  when:
    - pcie_passthrough_enable|bool
