---
- name: Install local dependencies for fstests command and control
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - python3-junitxml
      - python-pip

- name: Install junitparser
  become: true
  become_method: sudo
  pip:
    name:
      - junitparser
  when:
    - install_local_deps|bool
  tags: ["local_deps"]
