---
- name: Create a region from cxl memory
  become: true
  ansible.builtin.command: "cxl create-region -m -d decoder0.0 -w 1 mem0 -s 256M"
  tags: ["cxl-mem-setup"]

- name: Create a namespace from cxl memory
  become: true
  ansible.builtin.command: "ndctl create-namespace -m dax -r region0"
  tags: ["cxl-mem-setup"]

- name: Switch daxdevice to be used for system-ram
  become: true
  ansible.builtin.command: "daxctl reconfigure-device --mode=system-ram --no-online dax0.0"
  tags: ["cxl-mem-setup"]

- name: Online newly created daxdevice
  become: true
  ansible.builtin.command: "daxctl online-memory dax0.0"
  tags: ["cxl-mem-setup"]
