# SPDX-License-Identifier GPL-2.0+
---
nfsd_add_export_user: "root"
nfsd_add_export_group: "root"
nfsd_add_export_mode: "u=rwx,g=rwx,o=rwxt"
nfsd_add_export_pnfs: false

nfsd_export_storage_local: false
nfsd_export_storage_iscsi: false
