---
- name: Install partition creation base tools
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ packages }}"
  vars:
    packages:
      - xfsprogs
      - e2fsprogs

- name: Install btrfs-progs
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - btrfs-progs
  when: ansible_distribution == 'Fedora'
