---
- name: Enable fstests JUnit XML result processing
  hosts: localhost
  roles:
    - role: fstests_prep_localhost

- name: Configure and run the filesystem testing suite workflow
  hosts: baseline:dev
  roles:
    - role: fstests
