---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install dependencies
  ansible.builtin.import_tasks: install-deps/main.yml
- name: Git clone dbench
  ansible.builtin.git:
    repo: "{{ dbench_git }}"
    dest: "{{ dbench_data }}"
    update: true
  tags: ["git", "dbench"]
  when:
    - compile_dbench|bool

- name: Run autogen for dbench
  ansible.builtin.command: "./autogen.sh"
  tags: ["dbench"]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool

- name: Run configure for dbench
  ansible.builtin.command: "./configure"
  tags: ["dbench"]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool

- name: Get nproc
  ansible.builtin.command: "{{ num_jobs }}"
  tags: ["git", "dbench"]
  register: nproc
  when:
    - compile_dbench|bool

- name: Build dbench
  tags: ["git", "dbench"]
  community.general.make:
    chdir: "{{ dbench_data }}"
    jobs: "{{ nproc.stdout }}"
  when:
    - compile_dbench|bool

- name: Install dbench
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.command: "{{  make }} install"
  tags: ["git", "dbench"]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool
