---
- name: Import optional extra_args file
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "../extra_vars.yml"
        - "../extra_vars.yaml"
        - "../extra_vars.json"
      skip: true
  tags: vars

- name: Verify local build QEMU installation
  ansible.builtin.stat:
    path: "{{ qemu_bin_path }}"
  register: qemu_present
  changed_when: true
  failed_when: qemu_present.stat.exists and not qemu_present.stat.executable
  tags: ["qemu", "verify"]
  when:
    - qemu_build|bool

- name: Install build-deps for QEMU as per each Linux distribution
  ansible.builtin.include_tasks: install-deps/main.yml
  when:
    - qemu_build|bool
    - qemu_force_install_if_present|bool or not qemu_present.stat.exists

- name: Assume we won't build QEMU first
  ansible.builtin.set_fact:
    build_qemu_now: false
  tags: vars

- name: Annotate when we are building QEMU
  ansible.builtin.set_fact:
    build_qemu_now: true
  when:
    - qemu_build|bool
    - qemu_force_install_if_present|bool or (qemu_present.stat is not defined)
  tags: vars

- name: Ensure that {{ local_dev_path }} exists
  ansible.builtin.file:
    path: "{{ local_dev_path }}"
    state: directory
  tags: ["qemu", "build-deps"]
  when:
    - build_qemu_now|bool

- name: git clone QEMU using {{ qemu_git }} on {{ qemu_data }}
  environment:
    GIT_SSL_NO_VERIFY: true
  ansible.builtin.git:
    repo: "{{ qemu_git }}"
    dest: "{{ qemu_data }}"
    version: "{{ qemu_version }}"
  when:
    - build_qemu_now|bool

- name: Nuke old build directory
  ansible.builtin.file:
    path: "{{ qemu_build_dir }}"
    state: absent
  tags: ["qemu", "build-deps"]
  when:
    - build_qemu_now|bool

- name: Disable downloads
  ansible.builtin.command: "meson subprojects download"
  tags: ["qemu", "configure"]
  args:
    chdir: "{{ qemu_data }}"
  when:
    - build_qemu_now|bool

- name: Run configure for QEMU
  ansible.builtin.command: "./configure --target-list={{ qemu_target }} --disable-download"
  tags: ["qemu", "configure"]
  args:
    chdir: "{{ qemu_data }}"
  when:
    - build_qemu_now|bool

- name: Get nproc
  ansible.builtin.command: "{{ num_jobs }}"
  tags: ["qemu", "configure", "build"]
  register: nproc
  when:
    - build_qemu_now|bool

- name: Build QEMU
  community.general.make:
    chdir: "{{ qemu_data }}"
    jobs: "{{ nproc.stdout }}"
  tags: ["qemu", "build"]
  when:
    - build_qemu_now|bool

- name: Install QEMU
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.command: "{{ make }} install"
  args:
    chdir: "{{ qemu_data }}"
  tags: ["qemu", "install"]
  when:
    - build_qemu_now|bool
