---
- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: deps

- name: Install every single selftest build dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - gcc
      - bc
      - sed
      - git
      - gcc-multilib
      - libc6-i386
      - libc6-dev-i386
      - rsync
      - make
      - linux-perf
    state: present
    update_cache: true
  tags: ["selftests", "deps"]
