---
- name: Update apt cache
  become: true
  become_method: sudo
  apt:
    update_cache: true
  tags: linux

- name: Install generic kdevops deps
  become: true
  become_method: sudo
  apt:
    name:
      - gcc
      - make
      - bison
      - flex
      - m4
      - bc
      - sed
      - libncurses-dev
    state: present
    update_cache: true
  tags: ["kdevops", "deps"]
