---
- name: Install systemd-journal-remote
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    name:
      - systemd-journal-remote
  when:
    - devconfig_enable_systemd_journal_remote|bool
  tags: journal
