# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Reusable

on:
  workflow_call:
    inputs:
      ci_workflow:
        description: "CI Workflow"
        required: true
        default: 'blktests_nvme'
        type: string
      dir:
        description: 'Directory'
        required: true
        default: 'workdir'
        type: string
      kernel_ref:
        description: "Linux tree git reference (branch/tag/commit-id)"
        required: true
        default: 'master'
        type: string
      kernel_tree:
        description: "Linux kernel tree to use"
        required: true
        default: 'linux'
        type: string
      test_mode:
        description: 'Testing mode'
        required: false
        default: 'linux-ci'
        type: string
      tests:
        description: 'Custom test to run (for kdevops-ci mode only)'
        required: false
        default: ''
        type: string

jobs:
  setup:
    name: Setup kdevops workspace
    runs-on: ${{
        inputs.test_mode == 'kdevops-ci'
        && fromJSON('["self-hosted", "Linux", "X64", "kdevops-ci"]')
        || fromJSON('["self-hosted", "Linux", "X64", "linux-ci"]')
      }}
    steps:
      - name: kdevops setup
        uses: ./kdevops-run/.github/actions/setup
        with:
          ci_workflow: ${{ inputs.ci_workflow }}
          dir: ${{ inputs.dir }}
          kernel_ref: ${{ inputs.kernel_ref }}
          kernel_tree: ${{ inputs.kernel_tree }}
          test_mode: ${{ inputs.test_mode }}

  test:
    name: Run kdevops ci-test
    runs-on: ${{
        inputs.test_mode == 'kdevops-ci'
        && fromJSON('["self-hosted", "Linux", "X64", "kdevops-ci"]')
        || fromJSON('["self-hosted", "Linux", "X64", "linux-ci"]')
      }}
    needs: [setup]
    timeout-minutes: 120
    steps:
      - name: kdevops ci-test
        uses: ./kdevops-run/.github/actions/test
        with:
          ci_workflow: ${{ inputs.ci_workflow }}
          dir: ${{ inputs.ci_workflow }}-${{ github.run_id }}
          test_mode: ${{ inputs.test_mode }}
          tests: ${{ inputs.tests }}

  archive:
    name: Archive kdevops
    runs-on: ${{
        inputs.test_mode == 'kdevops-ci'
        && fromJSON('["self-hosted", "Linux", "X64", "kdevops-ci"]')
        || fromJSON('["self-hosted", "Linux", "X64", "linux-ci"]')
      }}
    needs: [setup, test]
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Archive ci-test results
        uses: ./kdevops-run/.github/actions/archive
        with:
          ci_workflow: ${{ inputs.ci_workflow }}
          dir: ${{ inputs.ci_workflow }}-${{ github.run_id }}

      - name: Upload our kdevops results archive
        uses: actions/upload-artifact@v4
        with:
          name: kdevops-ci-results
          path: ${{ inputs.ci_workflow }}-${{ github.run_id }}/kdevops/archive/*.zip

  cleanup:
    name: Cleanup kdevops workspace
    runs-on: ${{
        inputs.test_mode == 'kdevops-ci'
        && fromJSON('["self-hosted", "Linux", "X64", "kdevops-ci"]')
        || fromJSON('["self-hosted", "Linux", "X64", "linux-ci"]')
      }}
    needs: [setup, test, archive]
    if: always()
    steps:
      - name: kdevops cleanup
        uses: ./kdevops-run/.github/actions/cleanup
        with:
          dir: ${{ inputs.ci_workflow }}-${{ github.run_id }}
