# SPDX-License-Identifier: GPL-2.0
---
name: Test Push/PR Trigger

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test Job
    runs-on: [self-hosted]
    steps:
      - name: Test step
        run: |
          echo "Push/PR trigger is working!"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"