# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Push/PR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci-matrix:
    name: CI (${{ matrix.ci_workflow }})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        ci_workflow:
          - blktests_nvme
          - xfs_reflink_4k
    steps:
      - name: Checkout repository for ${{ matrix.ci_workflow }}
        shell: bash
        run: |
          set -euxo pipefail

          # More efficient approach similar to actions/checkout
          if [[ -d ".git" ]]; then
            # Repo exists - clean and fetch (like actions/checkout)
            git clean -ffdx
            git reset --hard HEAD
            # Ensure correct remote URL
            git remote set-url origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
            git fetch --depth=1 origin ${{ github.sha }}
            git checkout ${{ github.sha }}
          else
            # No repo - fresh clone with local mirror optimization
            if [[ -f "/mirror/kdevops.git/HEAD" ]]; then
              git clone --verbose --progress \
                --reference /mirror/kdevops.git \
                --depth=1 \
                $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
            else
              git clone --verbose --progress \
                --depth=1 \
                $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
            fi
          fi

      - name: kdevops setup
        uses: ./.github/actions/setup
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          kernel_ref: 'v6.15'
          kernel_tree: 'linux'
          test_mode: 'kdevops-ci'

      - name: kdevops ci-test
        uses: ./.github/actions/test
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          test_mode: 'kdevops-ci'
          tests: ''
        timeout-minutes: 120

      - name: kdevops archive
        uses: ./.github/actions/archive
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: kdevops cleanup
        if: always()
        uses: ./.github/actions/cleanup
