# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Push/PR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci-matrix:
    name: CI (${{ matrix.ci_workflow }})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        ci_workflow:
          - blktests_nvme
          - xfs_reflink_4k
    steps:
      - name: Checkout repository for ${{ matrix.ci_workflow }}
        run: |
          set -euxo pipefail
          git clean -ffdx || true
          git reset --hard HEAD || true

          if [[ -f "/mirror/kdevops.git/HEAD" ]]; then
            git clone --verbose --progress \
              --reference /mirror/kdevops.git \
              --depth=1 \
              $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
          else
            git clone --verbose --progress \
              --depth=1 \
              $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
          fi

      - name: kdevops setup
        uses: ./.github/actions/setup
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          kernel_ref: 'v6.15'
          kernel_tree: 'linux'
          test_mode: 'kdevops-ci'

      - name: kdevops ci-test
        uses: ./.github/actions/test
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          test_mode: 'kdevops-ci'
          tests: ''
        timeout-minutes: 120

      - name: kdevops archive
        uses: ./.github/actions/archive
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: kdevops cleanup
        if: always()
        uses: ./.github/actions/cleanup
