# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Push/PR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  checkout:
    runs-on: kdevops-ci
    steps:
      - name: Checkout kdevops
        run: |
          git clone --verbose --progress --depth=1 \
            --reference /mirror/kdevops.git \
            $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
            "${{ github.run_id }}-${{ github.run_number }}"

      - name: Symlink update
        run: |
          ln -sf \
            "${{ github.run_id }}-${{ github.run_number }}" \
            kdevops-run

      - name: Dummy test
        uses: ./kdevops-run/.github/actions/dummy
        with:
            dir: ${{ github.run_id }}-${{ github.run_number }}

      - name: Cleanup workdir and symlink
        if: always()   # ensure cleanup runs no matter what
        run: |
          rm -rfv "${{ github.run_id }}-${{ github.run_number }}"
          rm -fv "kdevops-run"
