# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Push/PR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  pushpr:
    name: Push/PR kdevops CI
    uses: ./.github/workflows/main.yml
    secrets: inherit
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        ci_workflow:
          - blktests_nvme
          - xfs_reflink_4k
    steps:
      - name: Checkout kdevops
        run: |
          set -euxo pipefail
          git clone --verbose --progress --depth=1 \
            --reference /mirror/kdevops.git \
            $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
            "kdevops-${{ github.run_id }}-${{ github.run_number }}"

      - name: Symlink update
        run: |
          set -euxo pipefail
          ln -sf \
            "${{ github.run_id }}-${{ github.run_number }}" \
            kdevops-run

      - name: Checkout kdevops
        uses: ./kdevops-run/.github/workflows/main
        with:
          ci_workflow: ${{ matrix.ci_workflow }}
          dir: ${{ github.run_id }}-${{ github.run_number }}
          kernel_ref: 'v6.15'
          kernel_tree: 'linux'
          test_mode: 'kdevops-ci'
          tests: ''

      - name: Cleanup workdir and symlink
        if: always()   # ensure cleanup runs no matter what
        run: |
          rm -rfv "${{ github.run_id }}-${{ github.run_number }}"
          rm -fv "kdevops-run"
