# SPDX-License-Identifier: GPL-2.0
---
name: Simple Test Workflow
on:
  push:
    branches:
      - ci-wip
  workflow_dispatch:
    inputs:
      ci_workflow:
        description: "CI Workflow"
        required: true
        default: 'blktests_nvme'
        type: string

jobs:
  simple-test:
    name: Simple kdevops test
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout kdevops to workspace (for actions)
        uses: actions/checkout@v4

      - name: Create unique working directory with git clone
        run: |
          echo "Creating unique working directory: run-${{ github.run_id }}"
          mkdir -p "run-${{ github.run_id }}"
          cd "run-${{ github.run_id }}"

          # Clone the repository into this directory
          git clone --branch ci-wip --single-branch https://github.com/dkruces/kdevops.git .

          echo "Working directory created and cloned successfully"
          ls -la

      - name: Simple setup with run_id
        uses: ./.github/actions/simple-setup
        with:
          ci_workflow: ${{ github.event.inputs.ci_workflow || 'blktests_nvme' }}
          work_dir: run-${{ github.run_id }}

      - name: Simple test execution
        uses: ./.github/actions/simple-test
        with:
          work_dir: run-${{ github.run_id }}

      - name: Simple cleanup
        if: always()
        uses: ./.github/actions/simple-cleanup
        with:
          work_dir: run-${{ github.run_id }}
